{
    'name': 'Witann - Access Control API', 
    'version': '19.0.2.0.67',
    'summary': 'API para validación de accesos (biometría / hardware)', 
    'category': 'Tools', 
    'author': 'Witann Technologies', 
    'license': 'LGPL-3', 
    'depends': ['base', 'web'], 
    'data': ['security/access_control_groups.xml',
             'security/ir.model.access.csv', 
             'views/access_control_menus.xml', 
             'views/access_control_site_views.xml', 
             'views/access_control_device_views.xml', 
             'views/access_control_person_views.xml', 
             'views/res_partner_access_views.xml',
    ], 
    'assets': {
        'web.assets_backend': [
            'access_control_api/static/src/js/face_camera_field.js',
            'access_control_api/static/src/xml/face_camera_field.xml',
        ],
    },
    'installable': True, 
    'application': True,
}
