{
    'name': 'Witann Group Subscriptions POS',
    'version': '19.0.1.5.168',
    'summary': 'Directorio y detalle de suscripciones nativas en Punto de Venta',
    'category': 'Point of Sale',
    'author': 'Witann Technologies',
    'license': 'LGPL-3',
    'depends': [
        'hr',
        'point_of_sale',
        'sale_subscription',
        'witann_group_subscriptions',
    ],
    'assets': {
        'point_of_sale._assets_pos': [
            'witann_group_subscriptions_pos/static/src/js/subscription_form_defaults.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_discount_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_pos_api.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_pricing_snapshot.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_ticket.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_pos_category_filter.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_view_utils.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_format_utils.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_modal_helpers.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_directory_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_access_log_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_directory_state.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_directory_controls.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_data_controllers.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_detail_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_detail_composer.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_card_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_partner_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_event_bindings.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_modal_state.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_partner_handlers.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_inline_form_handlers.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_flow_controllers.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_participants_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_renewal_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_upsale_render.js',
            'witann_group_subscriptions_pos/static/src/js/subscription_status_button.js',
            'witann_group_subscriptions_pos/static/src/xml/subscription_status_button.xml',
        ],
    },
    'installable': True,
    'application': False,
}
